version: '3.8'

services:
  document-remote-mcp:
    build: .
    container_name: document-remote-mcp
    ports:
      - "8080:8080"
    volumes:
      # Mount documents directory
      - ./development-guidelines:/app/documents/development-guidelines:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/mcp"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge